### ISSUE TITLE
Radar

### ISSUE THREAD

**Issue by Tomfuel** [KingOfIce77/KingRadar#2]
j'ai 3 moniteurs
mais seul 1 central declaré dans LFS (idem pour derinus), ya  que comme ça que ça s'affiche correct
1 27" central et 2 22" en side
tout LFS tout noir en mode fenetré et en mode plein ecran
dû en fait a overlay tout noir certainement (en visualisant apps avec Alt-tab
+ fenetre error impossible a atteindre car si je relache Alt tab, l'overlay tout noir reprend le dessus et recouvre

j'ai ecrit le mess error : 
Unhandled exception for scrit (titre)
Failed to execute scritp'radar only' due to unhandled exception 
name 'exit' is not defined
Traceback( most recet call last) : 
File "Radar_only.py", line 658, in <module>
NameError: name 'exit' is not defined

voila :-/

**Comment by KingOfIce77** [comment]
ok, mauvaise sortie en cas de check de version erroné.
Corrigé
